/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { HolidaysService } from "../holidays.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { HolidaysCreateInput } from "./HolidaysCreateInput";
import { Holidays } from "./Holidays";
import { HolidaysFindManyArgs } from "./HolidaysFindManyArgs";
import { HolidaysWhereUniqueInput } from "./HolidaysWhereUniqueInput";
import { HolidaysUpdateInput } from "./HolidaysUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class HolidaysControllerBase {
  constructor(
    protected readonly service: HolidaysService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Holidays })
  @nestAccessControl.UseRoles({
    resource: "Holidays",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createHolidays(
    @common.Body() data: HolidaysCreateInput
  ): Promise<Holidays> {
    return await this.service.createHolidays({
      data: data,
      select: {
        createdAt: true,
        date: true,
        id: true,
        name: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [Holidays] })
  @ApiNestedQuery(HolidaysFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "Holidays",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async holidaysItems(@common.Req() request: Request): Promise<Holidays[]> {
    const args = plainToClass(HolidaysFindManyArgs, request.query);
    return this.service.holidaysItems({
      ...args,
      select: {
        createdAt: true,
        date: true,
        id: true,
        name: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Holidays })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Holidays",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async holidays(
    @common.Param() params: HolidaysWhereUniqueInput
  ): Promise<Holidays | null> {
    const result = await this.service.holidays({
      where: params,
      select: {
        createdAt: true,
        date: true,
        id: true,
        name: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Holidays })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Holidays",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateHolidays(
    @common.Param() params: HolidaysWhereUniqueInput,
    @common.Body() data: HolidaysUpdateInput
  ): Promise<Holidays | null> {
    try {
      return await this.service.updateHolidays({
        where: params,
        data: data,
        select: {
          createdAt: true,
          date: true,
          id: true,
          name: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Holidays })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Holidays",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteHolidays(
    @common.Param() params: HolidaysWhereUniqueInput
  ): Promise<Holidays | null> {
    try {
      return await this.service.deleteHolidays({
        where: params,
        select: {
          createdAt: true,
          date: true,
          id: true,
          name: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
