/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { VacationsService } from "../vacations.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { VacationsCreateInput } from "./VacationsCreateInput";
import { Vacations } from "./Vacations";
import { VacationsFindManyArgs } from "./VacationsFindManyArgs";
import { VacationsWhereUniqueInput } from "./VacationsWhereUniqueInput";
import { VacationsUpdateInput } from "./VacationsUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class VacationsControllerBase {
  constructor(
    protected readonly service: VacationsService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Vacations })
  @nestAccessControl.UseRoles({
    resource: "Vacations",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createVacations(
    @common.Body() data: VacationsCreateInput
  ): Promise<Vacations> {
    return await this.service.createVacations({
      data: {
        ...data,

        user: data.user
          ? {
              connect: data.user,
            }
          : undefined,
      },
      select: {
        createdAt: true,
        endDate: true,
        id: true,
        startDate: true,
        typeField: true,
        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },

        workingDays: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [Vacations] })
  @ApiNestedQuery(VacationsFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "Vacations",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async vacationsItems(@common.Req() request: Request): Promise<Vacations[]> {
    const args = plainToClass(VacationsFindManyArgs, request.query);
    return this.service.vacationsItems({
      ...args,
      select: {
        createdAt: true,
        endDate: true,
        id: true,
        startDate: true,
        typeField: true,
        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },

        workingDays: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Vacations })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Vacations",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async vacations(
    @common.Param() params: VacationsWhereUniqueInput
  ): Promise<Vacations | null> {
    const result = await this.service.vacations({
      where: params,
      select: {
        createdAt: true,
        endDate: true,
        id: true,
        startDate: true,
        typeField: true,
        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },

        workingDays: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Vacations })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Vacations",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateVacations(
    @common.Param() params: VacationsWhereUniqueInput,
    @common.Body() data: VacationsUpdateInput
  ): Promise<Vacations | null> {
    try {
      return await this.service.updateVacations({
        where: params,
        data: {
          ...data,

          user: data.user
            ? {
                connect: data.user,
              }
            : undefined,
        },
        select: {
          createdAt: true,
          endDate: true,
          id: true,
          startDate: true,
          typeField: true,
          updatedAt: true,

          user: {
            select: {
              id: true,
            },
          },

          workingDays: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Vacations })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Vacations",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteVacations(
    @common.Param() params: VacationsWhereUniqueInput
  ): Promise<Vacations | null> {
    try {
      return await this.service.deleteVacations({
        where: params,
        select: {
          createdAt: true,
          endDate: true,
          id: true,
          startDate: true,
          typeField: true,
          updatedAt: true,

          user: {
            select: {
              id: true,
            },
          },

          workingDays: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
