/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { PaymentDetailsService } from "../paymentDetails.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { PaymentDetailsCreateInput } from "./PaymentDetailsCreateInput";
import { PaymentDetails } from "./PaymentDetails";
import { PaymentDetailsFindManyArgs } from "./PaymentDetailsFindManyArgs";
import { PaymentDetailsWhereUniqueInput } from "./PaymentDetailsWhereUniqueInput";
import { PaymentDetailsUpdateInput } from "./PaymentDetailsUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class PaymentDetailsControllerBase {
  constructor(
    protected readonly service: PaymentDetailsService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: PaymentDetails })
  @nestAccessControl.UseRoles({
    resource: "PaymentDetails",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createPaymentDetails(
    @common.Body() data: PaymentDetailsCreateInput
  ): Promise<PaymentDetails> {
    return await this.service.createPaymentDetails({
      data: {
        ...data,

        payment: data.payment
          ? {
              connect: data.payment,
            }
          : undefined,
      },
      select: {
        amount: true,
        createdAt: true,
        exchangeRate: true,
        id: true,

        payment: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [PaymentDetails] })
  @ApiNestedQuery(PaymentDetailsFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "PaymentDetails",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async paymentDetailsItems(
    @common.Req() request: Request
  ): Promise<PaymentDetails[]> {
    const args = plainToClass(PaymentDetailsFindManyArgs, request.query);
    return this.service.paymentDetailsItems({
      ...args,
      select: {
        amount: true,
        createdAt: true,
        exchangeRate: true,
        id: true,

        payment: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: PaymentDetails })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "PaymentDetails",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async paymentDetails(
    @common.Param() params: PaymentDetailsWhereUniqueInput
  ): Promise<PaymentDetails | null> {
    const result = await this.service.paymentDetails({
      where: params,
      select: {
        amount: true,
        createdAt: true,
        exchangeRate: true,
        id: true,

        payment: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: PaymentDetails })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "PaymentDetails",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updatePaymentDetails(
    @common.Param() params: PaymentDetailsWhereUniqueInput,
    @common.Body() data: PaymentDetailsUpdateInput
  ): Promise<PaymentDetails | null> {
    try {
      return await this.service.updatePaymentDetails({
        where: params,
        data: {
          ...data,

          payment: data.payment
            ? {
                connect: data.payment,
              }
            : undefined,
        },
        select: {
          amount: true,
          createdAt: true,
          exchangeRate: true,
          id: true,

          payment: {
            select: {
              id: true,
            },
          },

          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: PaymentDetails })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "PaymentDetails",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deletePaymentDetails(
    @common.Param() params: PaymentDetailsWhereUniqueInput
  ): Promise<PaymentDetails | null> {
    try {
      return await this.service.deletePaymentDetails({
        where: params,
        select: {
          amount: true,
          createdAt: true,
          exchangeRate: true,
          id: true,

          payment: {
            select: {
              id: true,
            },
          },

          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
