/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import {
  IsDate,
  IsOptional,
  IsString,
  MaxLength,
  IsEnum,
  ValidateNested,
} from "class-validator";
import { Type } from "class-transformer";
import { IsJSONValue } from "../../validators";
import { GraphQLJSON } from "graphql-type-json";
import { InputJsonValue } from "../../types";
import { EnumUserStatus } from "./EnumUserStatus";
import { UserPositionsUpdateManyWithoutUsersInput } from "./UserPositionsUpdateManyWithoutUsersInput";
import { UserProjectsUpdateManyWithoutUsersInput } from "./UserProjectsUpdateManyWithoutUsersInput";
import { VacationsUpdateManyWithoutUsersInput } from "./VacationsUpdateManyWithoutUsersInput";

@InputType()
class UserUpdateInput {
  @ApiProperty({
    required: false,
  })
  @IsDate()
  @Type(() => Date)
  @IsOptional()
  @Field(() => Date, {
    nullable: true,
  })
  dateOfBirth?: Date | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  email?: string | null;

  @ApiProperty({
    required: false,
  })
  @IsDate()
  @Type(() => Date)
  @IsOptional()
  @Field(() => Date, {
    nullable: true,
  })
  employmentEndDate?: Date | null;

  @ApiProperty({
    required: false,
  })
  @IsDate()
  @Type(() => Date)
  @IsOptional()
  @Field(() => Date, {
    nullable: true,
  })
  employmentStartDate?: Date | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  firstName?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  lastName?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  password?: string;

  @ApiProperty({
    required: false,
  })
  @IsJSONValue()
  @IsOptional()
  @Field(() => GraphQLJSON, {
    nullable: true,
  })
  roles?: InputJsonValue;

  @ApiProperty({
    required: false,
    enum: EnumUserStatus,
  })
  @IsEnum(EnumUserStatus)
  @IsOptional()
  @Field(() => EnumUserStatus, {
    nullable: true,
  })
  status?: "Option1" | null;

  @ApiProperty({
    required: false,
    type: () => UserPositionsUpdateManyWithoutUsersInput,
  })
  @ValidateNested()
  @Type(() => UserPositionsUpdateManyWithoutUsersInput)
  @IsOptional()
  @Field(() => UserPositionsUpdateManyWithoutUsersInput, {
    nullable: true,
  })
  userPositionsItems?: UserPositionsUpdateManyWithoutUsersInput;

  @ApiProperty({
    required: false,
    type: () => UserProjectsUpdateManyWithoutUsersInput,
  })
  @ValidateNested()
  @Type(() => UserProjectsUpdateManyWithoutUsersInput)
  @IsOptional()
  @Field(() => UserProjectsUpdateManyWithoutUsersInput, {
    nullable: true,
  })
  userProjectsItems?: UserProjectsUpdateManyWithoutUsersInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  username?: string;

  @ApiProperty({
    required: false,
    type: () => VacationsUpdateManyWithoutUsersInput,
  })
  @ValidateNested()
  @Type(() => VacationsUpdateManyWithoutUsersInput)
  @IsOptional()
  @Field(() => VacationsUpdateManyWithoutUsersInput, {
    nullable: true,
  })
  vacationsItems?: VacationsUpdateManyWithoutUsersInput;
}

export { UserUpdateInput as UserUpdateInput };
