/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { Payments } from "./Payments";
import { PaymentsCountArgs } from "./PaymentsCountArgs";
import { PaymentsFindManyArgs } from "./PaymentsFindManyArgs";
import { PaymentsFindUniqueArgs } from "./PaymentsFindUniqueArgs";
import { CreatePaymentsArgs } from "./CreatePaymentsArgs";
import { UpdatePaymentsArgs } from "./UpdatePaymentsArgs";
import { DeletePaymentsArgs } from "./DeletePaymentsArgs";
import { PaymentDetailsFindManyArgs } from "../../paymentDetails/base/PaymentDetailsFindManyArgs";
import { PaymentDetails } from "../../paymentDetails/base/PaymentDetails";
import { PaymentsService } from "../payments.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => Payments)
export class PaymentsResolverBase {
  constructor(
    protected readonly service: PaymentsService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "Payments",
    action: "read",
    possession: "any",
  })
  async _paymentsItemsMeta(
    @graphql.Args() args: PaymentsCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [Payments])
  @nestAccessControl.UseRoles({
    resource: "Payments",
    action: "read",
    possession: "any",
  })
  async paymentsItems(
    @graphql.Args() args: PaymentsFindManyArgs
  ): Promise<Payments[]> {
    return this.service.paymentsItems(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => Payments, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "Payments",
    action: "read",
    possession: "own",
  })
  async payments(
    @graphql.Args() args: PaymentsFindUniqueArgs
  ): Promise<Payments | null> {
    const result = await this.service.payments(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Payments)
  @nestAccessControl.UseRoles({
    resource: "Payments",
    action: "create",
    possession: "any",
  })
  async createPayments(
    @graphql.Args() args: CreatePaymentsArgs
  ): Promise<Payments> {
    return await this.service.createPayments({
      ...args,
      data: args.data,
    });
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Payments)
  @nestAccessControl.UseRoles({
    resource: "Payments",
    action: "update",
    possession: "any",
  })
  async updatePayments(
    @graphql.Args() args: UpdatePaymentsArgs
  ): Promise<Payments | null> {
    try {
      return await this.service.updatePayments({
        ...args,
        data: args.data,
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Payments)
  @nestAccessControl.UseRoles({
    resource: "Payments",
    action: "delete",
    possession: "any",
  })
  async deletePayments(
    @graphql.Args() args: DeletePaymentsArgs
  ): Promise<Payments | null> {
    try {
      return await this.service.deletePayments(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => [PaymentDetails], { name: "paymentDetailsItems" })
  @nestAccessControl.UseRoles({
    resource: "PaymentDetails",
    action: "read",
    possession: "any",
  })
  async findPaymentDetailsItems(
    @graphql.Parent() parent: Payments,
    @graphql.Args() args: PaymentDetailsFindManyArgs
  ): Promise<PaymentDetails[]> {
    const results = await this.service.findPaymentDetailsItems(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }
}
