/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { PaymentsService } from "../payments.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { PaymentsCreateInput } from "./PaymentsCreateInput";
import { Payments } from "./Payments";
import { PaymentsFindManyArgs } from "./PaymentsFindManyArgs";
import { PaymentsWhereUniqueInput } from "./PaymentsWhereUniqueInput";
import { PaymentsUpdateInput } from "./PaymentsUpdateInput";
import { PaymentDetailsFindManyArgs } from "../../paymentDetails/base/PaymentDetailsFindManyArgs";
import { PaymentDetails } from "../../paymentDetails/base/PaymentDetails";
import { PaymentDetailsWhereUniqueInput } from "../../paymentDetails/base/PaymentDetailsWhereUniqueInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class PaymentsControllerBase {
  constructor(
    protected readonly service: PaymentsService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Payments })
  @nestAccessControl.UseRoles({
    resource: "Payments",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createPayments(
    @common.Body() data: PaymentsCreateInput
  ): Promise<Payments> {
    return await this.service.createPayments({
      data: data,
      select: {
        amount: true,
        createdAt: true,
        date: true,
        description: true,
        id: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [Payments] })
  @ApiNestedQuery(PaymentsFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "Payments",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async paymentsItems(@common.Req() request: Request): Promise<Payments[]> {
    const args = plainToClass(PaymentsFindManyArgs, request.query);
    return this.service.paymentsItems({
      ...args,
      select: {
        amount: true,
        createdAt: true,
        date: true,
        description: true,
        id: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Payments })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Payments",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async payments(
    @common.Param() params: PaymentsWhereUniqueInput
  ): Promise<Payments | null> {
    const result = await this.service.payments({
      where: params,
      select: {
        amount: true,
        createdAt: true,
        date: true,
        description: true,
        id: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Payments })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Payments",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updatePayments(
    @common.Param() params: PaymentsWhereUniqueInput,
    @common.Body() data: PaymentsUpdateInput
  ): Promise<Payments | null> {
    try {
      return await this.service.updatePayments({
        where: params,
        data: data,
        select: {
          amount: true,
          createdAt: true,
          date: true,
          description: true,
          id: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Payments })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Payments",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deletePayments(
    @common.Param() params: PaymentsWhereUniqueInput
  ): Promise<Payments | null> {
    try {
      return await this.service.deletePayments({
        where: params,
        select: {
          amount: true,
          createdAt: true,
          date: true,
          description: true,
          id: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id/paymentDetailsItems")
  @ApiNestedQuery(PaymentDetailsFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "PaymentDetails",
    action: "read",
    possession: "any",
  })
  async findPaymentDetailsItems(
    @common.Req() request: Request,
    @common.Param() params: PaymentsWhereUniqueInput
  ): Promise<PaymentDetails[]> {
    const query = plainToClass(PaymentDetailsFindManyArgs, request.query);
    const results = await this.service.findPaymentDetailsItems(params.id, {
      ...query,
      select: {
        amount: true,
        createdAt: true,
        exchangeRate: true,
        id: true,

        payment: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/paymentDetailsItems")
  @nestAccessControl.UseRoles({
    resource: "Payments",
    action: "update",
    possession: "any",
  })
  async connectPaymentDetailsItems(
    @common.Param() params: PaymentsWhereUniqueInput,
    @common.Body() body: PaymentDetailsWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      paymentDetailsItems: {
        connect: body,
      },
    };
    await this.service.updatePayments({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/paymentDetailsItems")
  @nestAccessControl.UseRoles({
    resource: "Payments",
    action: "update",
    possession: "any",
  })
  async updatePaymentDetailsItems(
    @common.Param() params: PaymentsWhereUniqueInput,
    @common.Body() body: PaymentDetailsWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      paymentDetailsItems: {
        set: body,
      },
    };
    await this.service.updatePayments({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/paymentDetailsItems")
  @nestAccessControl.UseRoles({
    resource: "Payments",
    action: "update",
    possession: "any",
  })
  async disconnectPaymentDetailsItems(
    @common.Param() params: PaymentsWhereUniqueInput,
    @common.Body() body: PaymentDetailsWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      paymentDetailsItems: {
        disconnect: body,
      },
    };
    await this.service.updatePayments({
      where: params,
      data,
      select: { id: true },
    });
  }
}
